DROP TABLE CUSTOMER IF EXISTS;
DROP TABLE PET IF EXISTS;
DROP TABLE CUSTOMER_PET IF EXISTS;
DROP TABLE MEDICAL_HISTORY IF EXISTS;
DROP TABLE MEDICAL_HISTORY_PRODUCT IF EXISTS;
DROP TABLE VETERINARY_BILL IF EXISTS;